/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenii_p2_josueham;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreeNode;

/**
 *
 * @author skxka
 */
public class Main extends javax.swing.JFrame {

    private DefaultTreeModel modelo;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = (DefaultTreeModel) JTtorneos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopUpDeportes = new javax.swing.JPopupMenu();
        OpListarEquipos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        OpMostrarTabla = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTtorneos = new javax.swing.JTree();
        BtnCrearDeporte = new javax.swing.JButton();
        FieldNombreDeporte = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        OpListarEquipos.setText("Listar Equipos Participantes");
        PopUpDeportes.add(OpListarEquipos);
        PopUpDeportes.add(jSeparator1);

        OpMostrarTabla.setText("Mostrar Tabla de Posiciones");
        PopUpDeportes.add(OpMostrarTabla);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Torneos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q4");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q5");
        treeNode1.add(treeNode2);
        JTtorneos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTtorneos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTtorneosMouseClicked(evt);
            }
        });
        JTtorneos.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                JTtorneosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(JTtorneos);

        BtnCrearDeporte.setText("Crear Deporte");
        BtnCrearDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearDeporteActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del deporte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1)
                    .addComponent(FieldNombreDeporte)
                    .addComponent(BtnCrearDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FieldNombreDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCrearDeporte)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCrearDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearDeporteActionPerformed
        String nomDeporte = FieldNombreDeporte.getText();
        Deporte deporte = new Deporte(nomDeporte);

        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        DefaultMutableTreeNode Q1 = (DefaultMutableTreeNode) raiz.getChildAt(0);
        DefaultMutableTreeNode Q2 = (DefaultMutableTreeNode) raiz.getChildAt(1);
        DefaultMutableTreeNode Q4 = (DefaultMutableTreeNode) raiz.getChildAt(2);
        DefaultMutableTreeNode Q5 = (DefaultMutableTreeNode) raiz.getChildAt(3);
        
        DefaultMutableTreeNode dep1 = new DefaultMutableTreeNode(deporte);
        DefaultMutableTreeNode dep2 = new DefaultMutableTreeNode(deporte);
        DefaultMutableTreeNode dep3 = new DefaultMutableTreeNode(deporte);
        DefaultMutableTreeNode dep4 = new DefaultMutableTreeNode(deporte);
        
        Q1.add(dep1);
        Q2.add(dep2);
        Q4.add(dep3);
        Q5.add(dep4);
        modelo.reload();
        JOptionPane.showMessageDialog(this, "Deporte agregado");
    }//GEN-LAST:event_BtnCrearDeporteActionPerformed

    private void JTtorneosValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_JTtorneosValueChanged
        nodoSeleccionado = (DefaultMutableTreeNode) JTtorneos.getLastSelectedPathComponent();
    }//GEN-LAST:event_JTtorneosValueChanged

    private void JTtorneosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTtorneosMouseClicked
        if (evt.isMetaDown()) {
            if (nodoSeleccionado.getUserObject() instanceof Deporte) {
                PopUpDeportes.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_JTtorneosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void llenarDeportes() {

    }
    ArrayList<Deporte> deportes = new ArrayList<>();
    DefaultMutableTreeNode nodoSeleccionado;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearDeporte;
    private javax.swing.JTextField FieldNombreDeporte;
    private javax.swing.JTree JTtorneos;
    private javax.swing.JMenuItem OpListarEquipos;
    private javax.swing.JMenuItem OpMostrarTabla;
    private javax.swing.JPopupMenu PopUpDeportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
